id: "opoti:d"
initial_creation_type: input
base:
  - id: "B001"
    name:
      value: "volume 1"
      lang: "en"
    file: "bases/v001.txt"
  - id: "B002"
    name:
      value: "volume 2"
      lang: "en"
    file: "bases/v002.txt"